### PR TITLE
rewrite for WebSub, no FHIR Subscriptions

### PR DESCRIPTION
**Pull request by isaacvetter**
Rewrite spec to move away from using the FHIR server as the session management server ("hub"). Use WebSub and more generally, a webhooks pattern, in it's place.

### CODE REVIEW

**Comment by jeremysrichardson** [comment]
I see the ImagingStudy in context.  In reporting we don't have the DICOM UID available 99% of the time.  Reporting/RIS/PACS generally share context using Accession (and Assigning Authority).  I know @isaacvetter added it to the context b/c the cardinality of UID is 1..1, but practically it doesn't fit.

@NiklasSvenzen, within PACS, how would you model an ImagingStudy prior to receiving the DICOM (after you receive and HL7 v2 ORM)?
@isaacvetter how would this be modeled in RIS?  RIS would generally be ignorant of DICOM UID.

_For any subspecialty workflows that would act on DiagnosticReport/ImagingStudy Lab/RIS/PACS/Reporting, we need to have something like accession/order number. _

**Comment by jeremysrichardson** [comment]
Changes still don't cover one system on-site behind a firewall, one system in the cloud.  I think we will need a future treatment of the use case to be relevant by the time the spec reaches maturity.

**Comment by isaacvetter** [comment]
Hey @daliboz !

I haven't yet found the mental capacity to think through reusing FHIR Subscriptions. It's a neat idea, I'd love to think through it with you.

WebSub's discovery is nice and clean because the subscriber always visits the publisher first, before subscribing. I'm not sure that there's an analogy to our use-case.

I updated the PR to change topic to a URI and the examples to a url. 

I want to get this PR merged in for Connectathon participants. 

What do you think?

Isaac

**Comment by daliboz** [comment]
I think it's good to get it merged in to try out at the connectathon. +1

Thanks Isaac!

**Pull request merged**
